/**
 * Canonical FRAG guild roster. War data in data.js should only include these members
 * (plus GUILD_NAME_ALIASES for alternate in-game spellings).
 */
window.GUILD_ROSTER = [
  "Atmospheric",
  "Barbosass",
  "Beights",
  "Britannia",
  "Centurien",
  "CheekyBigKahuna",
  "Conlaoch",
  "Crowee",
  "CyberSword",
  "Dalua_Shd",
  "Darkiden",
  "DDE",
  "Deroxide",
  "Dragoneel",
  "DragonSouls",
  "DrShortstuf",
  "Eight76",
  "Eight_0hFoe",
  "FleitesFamily",
  "FxAxFxO",
  "GainTrain",
  "GhostMachine",
  "GodTamers",
  "GodlyHero",
  "GodZeebo",
  "Gourrrmet",
  "Grammatical",
  "Great_Nazaricks",
  "Hendo1114",
  "Hersheyyy",
  "Hestia758",
  "HouseofShield",
  "Iarsen",
  "IEtherealI",
  "Ikaroswolf",
  "Infernorage",
  "Interventionz",
  "IRunPockets",
  "Jaycro",
  "Jazz1118",
  "JoseFist",
  "Kilzuras",
  "Kinyon15",
  "Kitsune",
  "Ktcuda",
  "Lord_Blaze",
  "LordGrim",
  "MoonlitMocha",
  "MyFamilyName",
  "Netsrik",
  "Odaa",
  "PinguFamily",
  "PKs",
  "Polin",
  "Psychovasky",
  "Rajjnjack",
  "RealBanger",
  "REMEDY94",
  "Renegade69",
  "ShottaZz",
  "SinfulxJudgement",
  "SUBLIMIT",
  "Sugar",
  "Sunsorian",
  "Suspex",
  "TDOT23",
  "TheRossSauce",
  "Thinah",
  "Trackstarriq",
  "Treehugger",
  "Trooperr",
  "Umbrella",
  "Unagote",
  "Vector",
  "Verilan",
  "Whatsup",
  "Wintergreen2",
  "XSliceX",
  "Yuki_Chan",
  "Zoyac",
];

/** Member family name → team role */
window.GUILD_MEMBER_TEAMS = {
  Atmospheric: "Ball",
  Barbosass: "Ball",
  Beights: "Ball",
  Britannia: "Sailor",
  Centurien: "Ball",
  CheekyBigKahuna: "Flex",
  Conlaoch: "Support",
  Crowee: "Defense",
  CyberSword: "Ball",
  Dalua_Shd: "Ball",
  Darkiden: "Ball",
  DDE: "Ball",
  Deroxide: "Defense",
  Dragoneel: "Shotcaller, Support",
  DragonSouls: "Ball",
  DrShortstuf: "Support",
  Eight76: "Support",
  Eight_0hFoe: "Ball",
  FleitesFamily: "Ball",
  FxAxFxO: "Ball",
  GainTrain: "Ball",
  GhostMachine: "Ball",
  GodTamers: "Ball",
  GodlyHero: "Ball",
  GodZeebo: "Flex",
  Gourrrmet: "Ball",
  Grammatical: "Ball",
  Great_Nazaricks: "Flex",
  Hendo1114: "Sailor, Shai",
  Hersheyyy: "Ball",
  Hestia758: "Ball",
  HouseofShield: "Ball",
  Iarsen: "Ball",
  IEtherealI: "Defense",
  Ikaroswolf: "Ball",
  Infernorage: "D-Flex",
  Interventionz: "Ball",
  IRunPockets: "Ball",
  Jaycro: "Ball",
  Jazz1118: "Defense",
  JoseFist: "Ball",
  Kilzuras: "Ball",
  Kinyon15: "Ball",
  Kitsune: "Ball",
  Ktcuda: "Ball",
  Lord_Blaze: "Sailor",
  LordGrim: "D-Flex",
  MoonlitMocha: "Defense",
  MyFamilyName: "Sailor",
  Netsrik: "Defense",
  Odaa: "Shotcaller, Ball",
  PinguFamily: "Ball",
  PKs: "Flex, Ball",
  Polin: "Ball",
  Psychovasky: "Sailor",
  Rajjnjack: "Ball",
  RealBanger: "Ball",
  REMEDY94: "Support",
  Renegade69: "D-Flex",
  ShottaZz: "Support",
  SinfulxJudgement: "Support",
  SUBLIMIT: "Ball",
  Sugar: "Support",
  Sunsorian: "Ball",
  Suspex: "Ball",
  TDOT23: "Ball",
  TheRossSauce: "Support",
  Thinah: "Ball",
  Trackstarriq: "Flex",
  Treehugger: "Ball",
  Trooperr: "Ball",
  Umbrella: "Flex",
  Unagote: "Defense",
  Vector: "Ball",
  Verilan: "Ball",
  Whatsup: "Ball",
  Wintergreen2: "Flex",
  XSliceX: "Ball",
  Yuki_Chan: "Flex",
  Zoyac: "Support",
};

/** War result spelling → canonical roster name */
window.GUILD_NAME_ALIASES = {
  "Barbosas": "Barbosass",
  "Beighs": "Beights",
  "Brittainia": "Britannia",
  "CloudsRU": "CloudsRUs",
  "CloudsRUS": "CloudsRUs",
  "CM_YAMI": "CM_Yami",
  "Conladch": "Conlaoch",
  "Dalu_Shd": "Dalua_Shd",
  "Dalua_Shd": "Dalua_Shd",
  "Dalua_ShD": "Dalua_Shd",
  "Darkliden": "Darkiden",
  "Dragonjackfruit": "RealBanger",
  "DrShortstuff": "DrShortstuf",
  "Eight_OhFoe": "Eight_0hFoe",
  "FletesFamily": "FleitesFamily",
  "Gaterkiller": "Deroxide",
  "Gourrmet": "Gourrrmet",
  "Grelth": "Afary",
  "Hendol1114": "Hendo1114",
  "Hendol114": "Hendo1114",
  "Hypnotica": "Eight76",
  "Iarwen": "Iarsen",
  "IEthereal": "IEtherealI",
  "IEthereall": "IEtherealI",
  "Ikaraswolf": "Ikaroswolf",
  "Inferno": "Infernorage",
  "Intervention": "Interventionz",
  "ISlicel": "XSliceX",
  "iSlicel": "XSliceX",
  "Jed": "Dragoneel",
  "Jedrumer": "Dragoneel",
  "Jetscan": "Jetsecan",
  "Kahuna": "CheekyBigKahuna",
  "Kilnara": "Kilzuras",
  "Lareon": "Iarsen",
  "larion": "Iarsen",
  "larsen": "Iarsen",
  "LATINPOWWER": "LATINPOWER",
  "Lifengate": "Unagote",
  "Lordgrim": "LordGrim",
  "Lordooms": "Lord_Blaze",
  "Lordorian": "Lord_Blaze",
  "Lordurim": "LordGrim",
  "Nazaricks": "Great_Nazaricks",
  "nemesis": "NemesisProgram",
  "OkraLite": "Beights",
  "Palin": "Polin",
  "playboi": "PlxboiJ",
  "PlxyboiJ": "PlxboiJ",
  "PlyxboiJ": "PlxboiJ",
  "Podan": "Polin",
  "Polrn": "Polin",
  "Psychovsky": "Psychovasky",
  "Psychovsky_": "Psychovasky",
  "PvE_Polin": "Polin",
  "Rajinjack": "Rajjnjack",
  "renegade": "Renegade69",
  "Rosuno": "TheRossSauce",
  "Shottazz": "ShottaZz",
  "SoldierPer": "IEtherealI",
  "Sultanstrike": "Sunsorian",
  "Sursorian": "Sunsorian",
  "Tarren": "Trackstarriq",
  "trackstarr": "Trackstarriq",
  "Trackstartig": "Trackstarriq",
  "Trooper": "Trooperr",
  "TsukiCora": "Tsukicora",
  "Unknown": "Unknown_VII",
  "Unogote": "Unagote",
  "Vegy": "Vrey",
  "Vray": "Vrey",
  "Wintergreen": "Wintergreen2",
  "WorlBoss": "Worlboss",
  "X0daaX": "XOdaaX",
  "Zeebo": "GodZeebo",
  "Zenesis": "Crowee",
  "Zorgax": "Zoyac",
  "Zoya": "Zoyac",
  "Zoyae": "Zoyac",
};


/** Family name → BDO class (from guild roster PDF). */
window.GUILD_MEMBER_CLASS = {
  Atmospheric: "Sorceress",
  Barbosass: "Guardian",
  Beights: "Sage",
  Britannia: "Shai",
  Centurien: "Sage",
  CheekyBigKahuna: "Musa",
  Conlaoch: "Nova",
  Crowee: "Corsair",
  CyberSword: "Archer",
  Dalua_Shd: "Shai",
  Darkiden: "Kunoichi",
  DDE: "Berserker",
  Deroxide: "Striker",
  Dragoneel: "Wizard",
  DragonSouls: "Sage",
  DrShortstuf: "Dosa",
  Eight76: "Dosa",
  Eight_0hFoe: "Berserker",
  FleitesFamily: "Guardian",
  FxAxFxO: "Sage",
  GainTrain: "Sage",
  GhostMachine: "Sage",
  GodlyHero: "Sage",
  GodTamers: "Tamer",
  GodZeebo: "Hashashin",
  Gourrrmet: "Striker",
  Grammatical: "Striker",
  Great_Nazaricks: "Wukong",
  Hendo1114: "Shai",
  Hersheyyy: "Warrior",
  Hestia758: "Shai",
  HouseofShield: "Guardian",
  Iarsen: "Archer",
  IEtherealI: "Sorceress",
  Ikaroswolf: "Hashashin",
  Infernorage: "Sage",
  Interventionz: "Woosa",
  IRunPockets: "Sorceress",
  Jaycro: "Archer",
  Jazz1118: "Striker",
  Kinyon15: "Witch",
  Kitsune: "Maegu",
  Ktcuda: "Hashashin",
  Lord_Blaze: "Dark Knight",
  LordGrim: "Berserker",
  MoonlitMocha: "Sage",
  Netsrik: "Guardian",
  Odaa: "Guardian",
  PinguFamily: "Sage",
  PKs: "Sorceress",
  Polin: "Seraph",
  Psychovasky: "Wizard",
  Rajjnjack: "Dark Knight",
  REMEDY94: "Guardian",
  Renegade69: "Sage",
  SinfulxJudgement: "Wizard",
  SUBLIMIT: "Shai",
  Sugar: "Dosa",
  Sunsorian: "Ninja",
  Suspex: "Wizard",
  TDOT23: "Guardian",
  TheRossSauce: "Wizard",
  Thinah: "Guardian",
  Trackstarriq: "Striker",
  Treehugger: "Valkyrie",
  Umbrella: "Warrior",
  Unagote: "Sorceress",
  Vector: "Wizard",
  Verilan: "Wizard",
  Wintergreen2: "Maehwa",
  XSliceX: "Sorceress",
  Yuki_Chan: "Corsair",
  Zoyac: "Sage",
};

/** Family name → awakening / succession / ascension. */
window.GUILD_MEMBER_SPEC = {
  Atmospheric: "Awakening",
  Barbosass: "Awakening",
  Beights: "Succession",
  Britannia: "Ascension",
  Centurien: "Succession",
  CheekyBigKahuna: "Awakening",
  Conlaoch: "Succession",
  Crowee: "Succession",
  CyberSword: "Ascension",
  Dalua_Shd: "Ascension",
  Darkiden: "Awakening",
  DDE: "Succession",
  Deroxide: "Awakening",
  Dragoneel: "Succession",
  DragonSouls: "Succession",
  DrShortstuf: "Awakening",
  Eight76: "Awakening",
  Eight_0hFoe: "Awakening",
  FleitesFamily: "Awakening",
  FxAxFxO: "Succession",
  GainTrain: "Succession",
  GhostMachine: "Succession",
  GodlyHero: "Awakening",
  GodTamers: "Succession",
  GodZeebo: "Succession",
  Gourrrmet: "Awakening",
  Grammatical: "Awakening",
  Great_Nazaricks: "Ascension",
  Hendo1114: "Ascension",
  Hersheyyy: "Awakening",
  Hestia758: "Ascension",
  HouseofShield: "Awakening",
  Iarsen: "Ascension",
  IEtherealI: "Succession",
  Ikaroswolf: "Succession",
  Infernorage: "Awakening",
  Interventionz: "Awakening",
  IRunPockets: "Succession",
  Jaycro: "Ascension",
  Jazz1118: "Awakening",
  Kinyon15: "Awakening",
  Kitsune: "Succession",
  Ktcuda: "Awakening",
  Lord_Blaze: "Awakening",
  LordGrim: "Awakening",
  MoonlitMocha: "Awakening",
  Netsrik: "Awakening",
  Odaa: "Awakening",
  PinguFamily: "Succession",
  PKs: "Succession",
  Polin: "Ascension",
  Psychovasky: "Awakening",
  Rajjnjack: "Succession",
  REMEDY94: "Awakening",
  Renegade69: "Awakening",
  SinfulxJudgement: "Awakening",
  SUBLIMIT: "Ascension",
  Sugar: "Awakening",
  Sunsorian: "Awakening",
  Suspex: "Awakening",
  TDOT23: "Succession",
  TheRossSauce: "Awakening",
  Thinah: "Awakening",
  Trackstarriq: "Awakening",
  Treehugger: "Awakening",
  Umbrella: "Awakening",
  Unagote: "Succession",
  Vector: "Succession",
  Verilan: "Awakening",
  Wintergreen2: "Succession",
  XSliceX: "Awakening",
  Yuki_Chan: "Succession",
  Zoyac: "Succession",
};

/** Family name → Role in Ball (Frontline / Flanker / Backline / …). Notes column ignored. */
window.GUILD_MEMBER_BALL_ROLES = {
  Atmospheric: "Flanker",
  Barbosass: "Frontline",
  Beights: "Flanker",
  Britannia: "Shai",
  Centurien: "Flanker",
  CheekyBigKahuna: "Flanker",
  Conlaoch: "Frontline",
  Crowee: "Flanker",
  CyberSword: "Range",
  Dalua_Shd: "Shai",
  Darkiden: "Flanker",
  DDE: "Frontline",
  Deroxide: "Flanker",
  Dragoneel: "Frontline",
  DragonSouls: "Flanker",
  DrShortstuf: "Backline",
  Eight76: "Backline",
  Eight_0hFoe: "Flanker",
  FleitesFamily: "Frontline",
  FxAxFxO: "Flanker",
  GainTrain: "Flanker",
  GhostMachine: "Flanker",
  GodlyHero: "Flanker",
  GodTamers: "Flanker",
  GodZeebo: "Flanker",
  Gourrrmet: "Flanker",
  Grammatical: "Frontline",
  Great_Nazaricks: "Flanker",
  Hendo1114: "Shai",
  Hersheyyy: "Frontline",
  Hestia758: "Shai",
  HouseofShield: "Frontline",
  Iarsen: "Range",
  IEtherealI: "Flanker",
  Ikaroswolf: "Flanker",
  Infernorage: "Flanker",
  Interventionz: "Backline",
  IRunPockets: "Flanker",
  Jaycro: "Range",
  Jazz1118: "Flanker",
  Kinyon15: "Backline",
  Kitsune: "Flanker",
  Ktcuda: "Flanker",
  Lord_Blaze: "Backline",
  LordGrim: "Flanker",
  MoonlitMocha: "Flanker",
  Netsrik: "Frontline",
  Odaa: "Shotcaller",
  PinguFamily: "Flanker",
  PKs: "Flanker",
  Polin: "Frontline",
  Psychovasky: "Backline",
  Rajjnjack: "Frontline",
  REMEDY94: "Frontline",
  Renegade69: "Flanker",
  SinfulxJudgement: "Backline",
  SUBLIMIT: "Shai",
  Sugar: "Flanker",
  Sunsorian: "Flanker",
  Suspex: "Frontline",
  TDOT23: "Frontline",
  TheRossSauce: "Backline",
  Thinah: "Frontline",
  Trackstarriq: "Flanker",
  Treehugger: "Frontline",
  Umbrella: "Frontline",
  Unagote: "Frontline",
  Vector: "Frontline",
  Verilan: "Backline",
  Wintergreen2: "Flanker",
  XSliceX: "Flanker",
  Yuki_Chan: "Flanker",
  Zoyac: "Flanker",
};

/** Optional manual MVP exclusions (rare). Normal repeat rule is the cooldown below. */
window.GUILD_MVP_EXCLUDED = [
  "Trooperr", // left guild; war stats kept
];

/** Recorded monthly MVP winners (YYYY-MM). Used for repeat-win exclusion and analysis history. */
window.GUILD_MVP_WINNERS = {
  "2026-06": "Trooperr",
  "2026-07": "Iarsen",
};

/** Months a member must wait after winning before they can win MVP again. */
window.GUILD_MVP_COOLDOWN_MONTHS = 3;

/** Members cleared to compete before their normal post-win cooldown ends. */
window.GUILD_MVP_COOLDOWN_CLEARED = [
  "Trooperr",
];

/** Recorded monthly Healer MVP winners (YYYY-MM). Separate track from combat MVP. */
window.GUILD_HEALER_MVP_WINNERS = {};

/** First calendar month Healer MVP is tracked (YYYY-MM). Earlier months show no healer award. */
window.GUILD_HEALER_MVP_START_MONTH = "2026-08";

/** Months a member must wait after winning Healer MVP before they can win again. */
window.GUILD_HEALER_MVP_COOLDOWN_MONTHS = 1;
