/**
 * Canonical FRAG guild roster. War data in data.js should only include these members
 * (plus GUILD_NAME_ALIASES for alternate in-game spellings).
 */
window.GUILD_ROSTER = [
  "Afary",
  "Atmospheric",
  "AyanamiRei",
  "Beights",
  "Belovedd",
  "Britannia",
  "Centurien",
  "CheekyBigKahuna",
  "CM_Yami",
  "Coldest",
  "Coldsin",
  "CloudsRUs",
  "Conlaoch",
  "CrizpeeCreme",
  "Crowee",
  "Darkiden",
  "DDE",
  "Dalua_Shd",
  "Deroxide",
  "Dragoneel",
  "DrShortstuf",
  "Eight76",
  "Efface",
  "FleitesFamily",
  "GodZeebo",
  "GhostMachine",
  "Grammatical",
  "Great_Nazaricks",
  "Gourrrmet",
  "Hadeez",
  "Hendo1114",
  "Hersheyyy",
  "HolyTrinity",
  "HouseofShield",
  "Iarsen",
  "IEtherealI",
  "Ikaroswolf",
  "Infernorage",
  "Interventionz",
  "Jaycro",
  "Jazz1118",
  "Jetsecan",
  "JoseFist",
  "Kilzuras",
  "Kinyon15",
  "Kitsune",
  "Koisenso",
  "Kyln",
  "Lord_Blaze",
  "LordGrim",
  "Marszarukky",
  "Mikami",
  "MoonlitMocha",
  "MyFamilyName",
  "NemesisProgram",
  "Netsrik",
  "NonToxicPlayer",
  "Odaa",
  "Odin_Clan",
  "PinguFamily",
  "Pivva",
  "PKs",
  "PlxboiJ",
  "Polin",
  "Psychovasky",
  "RealBanger",
  "REMEDY94",
  "Renegade69",
  "Rxckless",
  "Shadowfang",
  "ShottaZz",
  "SinfulxJudgement",
  "Sugar",
  "Sunsorian",
  "TheRossSauce",
  "Trackstarriq",
  "Treehugger",
  "Trooperr",
  "Tsukicora",
  "Tyagi",
  "UmbralFox",
  "Umbrella",
  "Unagote",
  "Unknown_VII",
  "Verilan",
  "Vrey",
  "Warp",
  "Wackthetripper",
  "Wintergreen2",
  "Wints",
  "Worlboss",
  "XChronik",
  "XOdaaX",
  "XSliceX",
  "XxCASHxX",
  "Yuki_Chan",
  "Zoyac",
];

/** Member family name → team role */
window.GUILD_MEMBER_TEAMS = {
  Afary: "Flag Placer",
  Atmospheric: "Ball",
  AyanamiRei: "Ball",
  Beights: "Ball",
  Belovedd: "Ball",
  Britannia: "Sailor",
  Centurien: "Ball",
  CheekyBigKahuna: "Flex",
  CM_Yami: "Ball",
  Coldest: "Ball",
  Coldsin: "D-Flex",
  CloudsRUs: "Ball",
  Conlaoch: "Support",
  CrizpeeCreme: "Ball",
  Crowee: "Defense",
  Darkiden: "Ball",
  DDE: "Ball",
  Dalua_Shd: "Ball",
  Deroxide: "Defense",
  Dragoneel: "Shotcaller, Support",
  DrShortstuf: "Support",
  Eight76: "Shai",
  Efface: "Ball",
  FleitesFamily: "Ball",
  GodZeebo: "Flex",
  GhostMachine: "Ball",
  Grammatical: "Ball",
  Great_Nazaricks: "Flex",
  Gourrrmet: "Ball",
  Hadeez: "Ball",
  Hendo1114: "Sailor",
  Hersheyyy: "Ball",
  HolyTrinity: "Cannons",
  HouseofShield: "Ball",
  Iarsen: "Ball",
  IEtherealI: "Defense",
  Ikaroswolf: "Ball",
  Infernorage: "D-Flex",
  Interventionz: "Ball",
  Jaycro: "Ball",
  Jazz1118: "Defense",
  Jetsecan: "Support",
  JoseFist: "Ball",
  Kilzuras: "Ball",
  Kinyon15: "Support",
  Kitsune: "Ball",
  Koisenso: "Ball",
  Kyln: "Ball",
  Lord_Blaze: "Sailor",
  LordGrim: "D-Flex",
  Marszarukky: "Ball",
  Mikami: "Ball",
  MoonlitMocha: "Defense",
  MyFamilyName: "Sailor",
  NemesisProgram: "D-Flex",
  Netsrik: "Defense",
  NonToxicPlayer: "Ball",
  Odaa: "Shotcaller, Ball",
  Odin_Clan: "Ball",
  PinguFamily: "Ball",
  Pivva: "Support",
  PKs: "Flex, Ball",
  PlxboiJ: "D-Flex",
  Polin: "Ball",
  Psychovasky: "Sailor",
  RealBanger: "Ball",
  REMEDY94: "Support",
  Renegade69: "D-Flex",
  Rxckless: "Ball",
  Shadowfang: "Defense",
  ShottaZz: "Support",
  SinfulxJudgement: "Support",
  Sugar: "Support",
  Sunsorian: "Ball",
  TheRossSauce: "Support",
  Trackstarriq: "Flex",
  Treehugger: "Ball",
  Trooperr: "Ball",
  Tsukicora: "Ball",
  Tyagi: "Ball",
  UmbralFox: "Support",
  Umbrella: "Flex",
  Unagote: "Defense",
  Unknown_VII: "Support",
  Verilan: "Ball",
  Vrey: "Shotcaller",
  Warp: "Ball",
  Wackthetripper: "Ball",
  Wintergreen2: "Flex",
  Wints: "Ball",
  Worlboss: "Defense",
  XChronik: "Defense",
  XOdaaX: "Ball",
  XSliceX: "Ball",
  XxCASHxX: "Ball",
  Yuki_Chan: "Flex",
  Zoyac: "Support",
};

/** War result spelling → canonical roster name */
window.GUILD_NAME_ALIASES = {
  "Ayuandeimo": "AyanamiRei",
  "Beighs": "Beights",
  "Brittainia": "Britannia",
  "CloudsRU": "CloudsRUs",
  "CloudsRUS": "CloudsRUs",
  "Conladch": "Conlaoch",
  "CM_YAMI": "CM_Yami",
  "Dalua_Shd": "Dalua_Shd",
  "Darkliden": "Darkiden",
  "Dalu_Shd": "Dalua_Shd",
  "DrShortstuff": "DrShortstuf",
  "FletesFamily": "FleitesFamily",
  "Dragonjackfruit": "RealBanger",
  "Gaterkiller": "Deroxide",
  "Grelth": "Afary",
  "Holy Trinity": "HolyTrinity",
  "Hypnotica": "Eight76",
  "Iarwen": "Iarsen",
  "IEthereal": "IEtherealI",
  "IEthereall": "IEtherealI",
  "Ikaraswolf": "Ikaroswolf",
  "Inferno": "Infernorage",
  "Jed": "Dragoneel",
  "Jedrumer": "Dragoneel",
  "Kahuna": "CheekyBigKahuna",
  "Kilnara": "Kilzuras",
  "Lareon": "Iarsen",
  "larion": "Iarsen",
  "larsen": "Iarsen",
  "Lifengate": "Unagote",
  "Lordgrim": "LordGrim",
  "Lordooms": "Lord_Blaze",
  "Lordorian": "Lord_Blaze",
  "Lordurim": "LordGrim",
  "Lumpa": "Kinyon15",
  "Nazaricks": "Great_Nazaricks",
  "nemesis": "NemesisProgram",
  "Odin Clan": "Odin_Clan",
  "odin_Clan": "Odin_Clan",
  "OkraLite": "Beights",
  "Palin": "Polin",
  "playboi": "PlxboiJ",
  "PlxyboiJ": "PlxboiJ",
  "PlyxboiJ": "PlxboiJ",
  "Podan": "Polin",
  "PvE_Polin": "Polin",
  "Polrn": "Polin",
  "Psychovsky": "Psychovasky",
  "Psychovsky_": "Psychovasky",
  "renegade": "Renegade69",
  "Rosuno": "TheRossSauce",
  "Shottazz": "ShottaZz",
  "SoldierPer": "IEtherealI",
  "Sultanstrike": "Sunsorian",
  "Tarren": "Trackstarriq",
  "Trooper": "Trooperr",
  "TsukiCora": "Tsukicora",
  "trackstarr": "Trackstarriq",
  "Trackstartig": "Trackstarriq",
  "Unknown": "Unknown_VII",
  "UmbraIFox": "UmbralFox",
  "Unogote": "Unagote",
  "Vegy": "Vrey",
  "Vray": "Vrey",
  "Wintergreen": "Wintergreen2",
  "WorlBoss": "Worlboss",
  "Zeebo": "GodZeebo",
  "Zenesis": "Crowee",
  "Zorgax": "Zoyac",
  "Zoya": "Zoyac",
  "Zoyae": "Zoyac",
};
