/**
 * Canonical FRAG guild roster. War data in data.js should only include these members
 * (plus GUILD_NAME_ALIASES for alternate in-game spellings).
 */
window.GUILD_ROSTER = [
  "Atmospheric",
  "Barbosass",
  "Beights",
  "Britannia",
  "Centurien",
  "CheekyBigKahuna",
  "Conlaoch",
  "Crowee",
  "CyberSword",
  "Dalua_Shd",
  "Darkiden",
  "DDE",
  "Deroxide",
  "Dragoneel",
  "DrShortstuf",
  "Eight76",
  "Eight_0hFoe",
  "FleitesFamily",
  "GainTrain",
  "GhostMachine",
  "GodTamers",
  "GodZeebo",
  "Gourrrmet",
  "Grammatical",
  "Great_Nazaricks",
  "Hendo1114",
  "Hersheyyy",
  "Hestia758",
  "HouseofShield",
  "Iarsen",
  "IEtherealI",
  "Ikaroswolf",
  "Infernorage",
  "Interventionz",
  "IRunPockets",
  "Jaycro",
  "Jazz1118",
  "JoseFist",
  "Kilzuras",
  "Kinyon15",
  "Kitsune",
  "Ktcuda",
  "Lord_Blaze",
  "LordGrim",
  "MoonlitMocha",
  "MyFamilyName",
  "Netsrik",
  "Odaa",
  "PinguFamily",
  "PKs",
  "Polin",
  "Psychovasky",
  "Rajjnjack",
  "RealBanger",
  "REMEDY94",
  "Renegade69",
  "ShottaZz",
  "SinfulxJudgement",
  "SUBLIMIT",
  "Sugar",
  "Sunsorian",
  "Suspex",
  "TDOT23",
  "TheRossSauce",
  "Thinah",
  "Trackstarriq",
  "Treehugger",
  "Trooperr",
  "Umbrella",
  "Unagote",
  "Vector",
  "Verilan",
  "Whatsup",
  "Wintergreen2",
  "XSliceX",
  "Yuki_Chan",
  "Zoyac",
];

/** Member family name → team role */
window.GUILD_MEMBER_TEAMS = {
  Atmospheric: "Ball",
  Barbosass: "Ball",
  Beights: "Ball",
  Britannia: "Sailor",
  Centurien: "Ball",
  CheekyBigKahuna: "Flex",
  Conlaoch: "Support",
  Crowee: "Defense",
  CyberSword: "Ball",
  Dalua_Shd: "Ball",
  Darkiden: "Ball",
  DDE: "Ball",
  Deroxide: "Defense",
  Dragoneel: "Shotcaller, Support",
  DrShortstuf: "Support",
  Eight76: "Support",
  Eight_0hFoe: "Ball",
  FleitesFamily: "Ball",
  GainTrain: "Ball",
  GhostMachine: "Ball",
  GodTamers: "Ball",
  GodZeebo: "Flex",
  Gourrrmet: "Ball",
  Grammatical: "Ball",
  Great_Nazaricks: "Flex",
  Hendo1114: "Sailor, Shai",
  Hersheyyy: "Ball",
  Hestia758: "Ball",
  HouseofShield: "Ball",
  Iarsen: "Ball",
  IEtherealI: "Defense",
  Ikaroswolf: "Ball",
  Infernorage: "D-Flex",
  Interventionz: "Ball",
  IRunPockets: "Ball",
  Jaycro: "Ball",
  Jazz1118: "Defense",
  JoseFist: "Ball",
  Kilzuras: "Ball",
  Kinyon15: "Ball",
  Kitsune: "Ball",
  Ktcuda: "Ball",
  Lord_Blaze: "Sailor",
  LordGrim: "D-Flex",
  MoonlitMocha: "Defense",
  MyFamilyName: "Sailor",
  Netsrik: "Defense",
  Odaa: "Shotcaller, Ball",
  PinguFamily: "Ball",
  PKs: "Flex, Ball",
  Polin: "Ball",
  Psychovasky: "Sailor",
  Rajjnjack: "Ball",
  RealBanger: "Ball",
  REMEDY94: "Support",
  Renegade69: "D-Flex",
  ShottaZz: "Support",
  SinfulxJudgement: "Support",
  SUBLIMIT: "Ball",
  Sugar: "Support",
  Sunsorian: "Ball",
  Suspex: "Ball",
  TDOT23: "Ball",
  TheRossSauce: "Support",
  Thinah: "Ball",
  Trackstarriq: "Flex",
  Treehugger: "Ball",
  Trooperr: "Ball",
  Umbrella: "Flex",
  Unagote: "Defense",
  Vector: "Ball",
  Verilan: "Ball",
  Whatsup: "Ball",
  Wintergreen2: "Flex",
  XSliceX: "Ball",
  Yuki_Chan: "Flex",
  Zoyac: "Support",
};

/** War result spelling → canonical roster name */
window.GUILD_NAME_ALIASES = {
  "Barbosas": "Barbosass",
  "Beighs": "Beights",
  "Brittainia": "Britannia",
  "CloudsRU": "CloudsRUs",
  "CloudsRUS": "CloudsRUs",
  "CM_YAMI": "CM_Yami",
  "Conladch": "Conlaoch",
  "Dalu_Shd": "Dalua_Shd",
  "Dalua_Shd": "Dalua_Shd",
  "Dalua_ShD": "Dalua_Shd",
  "Darkliden": "Darkiden",
  "Dragonjackfruit": "RealBanger",
  "DrShortstuff": "DrShortstuf",
  "Eight_OhFoe": "Eight_0hFoe",
  "FletesFamily": "FleitesFamily",
  "Gaterkiller": "Deroxide",
  "Gourrmet": "Gourrrmet",
  "Grelth": "Afary",
  "Hendol1114": "Hendo1114",
  "Hendol114": "Hendo1114",
  "Hypnotica": "Eight76",
  "Iarwen": "Iarsen",
  "IEthereal": "IEtherealI",
  "IEthereall": "IEtherealI",
  "Ikaraswolf": "Ikaroswolf",
  "Inferno": "Infernorage",
  "ISlicel": "XSliceX",
  "iSlicel": "XSliceX",
  "Jed": "Dragoneel",
  "Jedrumer": "Dragoneel",
  "Jetscan": "Jetsecan",
  "Kahuna": "CheekyBigKahuna",
  "Kilnara": "Kilzuras",
  "Lareon": "Iarsen",
  "larion": "Iarsen",
  "larsen": "Iarsen",
  "LATINPOWWER": "LATINPOWER",
  "Lifengate": "Unagote",
  "Lordgrim": "LordGrim",
  "Lordooms": "Lord_Blaze",
  "Lordorian": "Lord_Blaze",
  "Lordurim": "LordGrim",
  "Nazaricks": "Great_Nazaricks",
  "nemesis": "NemesisProgram",
  "OkraLite": "Beights",
  "Palin": "Polin",
  "playboi": "PlxboiJ",
  "PlxyboiJ": "PlxboiJ",
  "PlyxboiJ": "PlxboiJ",
  "Podan": "Polin",
  "Polrn": "Polin",
  "Psychovsky": "Psychovasky",
  "Psychovsky_": "Psychovasky",
  "PvE_Polin": "Polin",
  "Rajinjack": "Rajjnjack",
  "renegade": "Renegade69",
  "Rosuno": "TheRossSauce",
  "Shottazz": "ShottaZz",
  "SoldierPer": "IEtherealI",
  "Sultanstrike": "Sunsorian",
  "Sursorian": "Sunsorian",
  "Tarren": "Trackstarriq",
  "trackstarr": "Trackstarriq",
  "Trackstartig": "Trackstarriq",
  "Trooper": "Trooperr",
  "TsukiCora": "Tsukicora",
  "Unknown": "Unknown_VII",
  "Unogote": "Unagote",
  "Vegy": "Vrey",
  "Vray": "Vrey",
  "Wintergreen": "Wintergreen2",
  "WorlBoss": "Worlboss",
  "X0daaX": "XOdaaX",
  "Zeebo": "GodZeebo",
  "Zenesis": "Crowee",
  "Zorgax": "Zoyac",
  "Zoya": "Zoyac",
  "Zoyae": "Zoyac",
};

/** Optional manual MVP exclusions (rare). Normal repeat rule is the cooldown below. */
window.GUILD_MVP_EXCLUDED = [];

/** Recorded monthly MVP winners (YYYY-MM). Used for repeat-win exclusion and analysis history. */
window.GUILD_MVP_WINNERS = {
  "2026-06": "Trooperr",
  "2026-07": "Iarsen",
};

/** Months a member must wait after winning before they can win MVP again. */
window.GUILD_MVP_COOLDOWN_MONTHS = 3;

/** Members cleared to compete before their normal post-win cooldown ends. */
window.GUILD_MVP_COOLDOWN_CLEARED = [
  "Trooperr",
];

/** Recorded monthly Healer MVP winners (YYYY-MM). Separate track from combat MVP. */
window.GUILD_HEALER_MVP_WINNERS = {};

/** First calendar month Healer MVP is tracked (YYYY-MM). Earlier months show no healer award. */
window.GUILD_HEALER_MVP_START_MONTH = "2026-08";

/** Months a member must wait after winning Healer MVP before they can win again. */
window.GUILD_HEALER_MVP_COOLDOWN_MONTHS = 1;
